from __future__ import annotations

from .tokens import Token, TokenKind

KEYWORDS: dict[str, tuple[TokenKind, object | None]] = {
    "abstract": (TokenKind.ABSTRACT, None),
    "and": (TokenKind.AND, None),
    "as": (TokenKind.AS, None),
    "assert": (TokenKind.ASSERT, None),
    "base": (TokenKind.BASE, None),
    "begin": (TokenKind.BEGIN, None),
    "class": (TokenKind.CLASS, None),
    "const": (TokenKind.CONST, None),
    "default": (TokenKind.DEFAULT, None),
    "delegate": (TokenKind.DELEGATE, None),
    "do": (TokenKind.DO, None),
    "done": (TokenKind.DONE, None),
    "downcast": (TokenKind.DOWNCAST, None),
    "downto": (TokenKind.DOWNTO, None),
    "elif": (TokenKind.ELIF, None),
    "else": (TokenKind.ELSE, None),
    "end": (TokenKind.END, None),
    "exception": (TokenKind.EXCEPTION, None),
    "extern": (TokenKind.EXTERN, None),
    "false": (TokenKind.FALSE, None),
    "finally": (TokenKind.FINALLY, None),
    "fixed": (TokenKind.FIXED, None),
    "for": (TokenKind.FOR, None),
    "fun": (TokenKind.FUN, None),
    "function": (TokenKind.FUNCTION, None),
    "global": (TokenKind.GLOBAL, None),
    "if": (TokenKind.IF, None),
    "in": (TokenKind.IN, None),
    "inherit": (TokenKind.INHERIT, None),
    "inline": (TokenKind.INLINE, None),
    "interface": (TokenKind.INTERFACE, None),
    "internal": (TokenKind.INTERNAL, None),
    "lazy": (TokenKind.LAZY, None),
    "let": (TokenKind.LET, False),
    "match": (TokenKind.MATCH, None),
    "member": (TokenKind.MEMBER, None),
    "mod": (TokenKind.INFIX_STAR_DIV_MOD_OP, "mod"),
    "module": (TokenKind.MODULE, None),
    "mutable": (TokenKind.MUTABLE, None),
    "namespace": (TokenKind.NAMESPACE, None),
    "new": (TokenKind.NEW, None),
    "null": (TokenKind.NULL, None),
    "of": (TokenKind.OF, None),
    "open": (TokenKind.OPEN, None),
    "or": (TokenKind.OR, None),
    "override": (TokenKind.OVERRIDE, None),
    "private": (TokenKind.PRIVATE, None),
    "public": (TokenKind.PUBLIC, None),
    "rec": (TokenKind.REC, None),
    "return": (TokenKind.YIELD, False),
    "sig": (TokenKind.SIG, None),
    "static": (TokenKind.STATIC, None),
    "struct": (TokenKind.STRUCT, None),
    "then": (TokenKind.THEN, None),
    "to": (TokenKind.TO, None),
    "true": (TokenKind.TRUE, None),
    "try": (TokenKind.TRY, None),
    "type": (TokenKind.TYPE, None),
    "upcast": (TokenKind.UPCAST, None),
    "use": (TokenKind.LET, True),
    "val": (TokenKind.VAL, None),
    "void": (TokenKind.VOID, None),
    "when": (TokenKind.WHEN, None),
    "while": (TokenKind.WHILE, None),
    "with": (TokenKind.WITH, None),
    "yield": (TokenKind.YIELD, True),
    "_": (TokenKind.UNDERSCORE, None),
    "__token_OBLOCKSEP": (TokenKind.OBLOCKSEP, None),
    "__token_OWITH": (TokenKind.OWITH, None),
    "__token_ODECLEND": (TokenKind.ODECLEND, None),
    "__token_OTHEN": (TokenKind.OTHEN, None),
    "__token_OELSE": (TokenKind.OELSE, None),
    "__token_OEND": (TokenKind.OEND, None),
    "__token_ODO": (TokenKind.ODO, None),
    "__token_OLET": (TokenKind.OLET, True),
    "__token_constraint": (TokenKind.CONSTRAINT, None),
}

RESERVED = {
    "break",
    "checked",
    "component",
    "constraint",
    "continue",
    "fori",
    "include",
    "mixin",
    "parallel",
    "params",
    "process",
    "protected",
    "pure",
    "sealed",
    "trait",
    "tailcall",
    "virtual",
}


def keyword_or_identifier(text: str, range_) -> Token:
    if text in KEYWORDS:
        kind, value = KEYWORDS[text]
        return Token(kind, value, range_, text)
    if text in RESERVED:
        return Token(TokenKind.IDENT, text, range_, text)
    if text in {"__SOURCE_DIRECTORY__", "__SOURCE_FILE__", "__LINE__"}:
        return Token(TokenKind.KEYWORD_STRING, (text, ""), range_, text)
    return Token(TokenKind.IDENT, text, range_, text)
