from __future__ import annotations

from collections.abc import Iterable

from .tokens import Token, TokenKind

OFFICIAL_TOKEN_TAGS: dict[TokenKind, int] = {
    TokenKind.HASH_IF: 0,
    TokenKind.HASH_ELSE: 1,
    TokenKind.HASH_ENDIF: 2,
    TokenKind.HASH_ELIF: 3,
    TokenKind.WARN_DIRECTIVE: 4,
    TokenKind.COMMENT: 5,
    TokenKind.WHITESPACE: 6,
    TokenKind.HASH_LINE: 7,
    TokenKind.INACTIVECODE: 8,
    TokenKind.LINE_COMMENT: 9,
    TokenKind.STRING_TEXT: 10,
    TokenKind.EOF: 11,
    TokenKind.LEX_FAILURE: 12,
    TokenKind.ODUMMY: 13,
    TokenKind.FIXED: 14,
    TokenKind.OINTERFACE_MEMBER: 15,
    TokenKind.OBLOCKEND_COMING_SOON: 16,
    TokenKind.OBLOCKEND_IS_HERE: 17,
    TokenKind.OBLOCKEND: 18,
    TokenKind.ORIGHT_BLOCK_END: 19,
    TokenKind.ODECLEND: 20,
    TokenKind.OEND: 21,
    TokenKind.OBLOCKSEP: 22,
    TokenKind.OBLOCKBEGIN: 23,
    TokenKind.ORESET: 24,
    TokenKind.OFUN: 25,
    TokenKind.OFUNCTION: 26,
    TokenKind.OWITH: 27,
    TokenKind.OELSE: 28,
    TokenKind.OTHEN: 29,
    TokenKind.ODO_BANG: 30,
    TokenKind.ODO: 31,
    TokenKind.OAND_BANG: 32,
    TokenKind.OBINDER: 33,
    TokenKind.OLET: 34,
    TokenKind.HIGH_PRECEDENCE_TYAPP: 35,
    TokenKind.HIGH_PRECEDENCE_PAREN_APP: 36,
    TokenKind.HIGH_PRECEDENCE_BRACK_APP: 37,
    TokenKind.TYPE_COMING_SOON: 38,
    TokenKind.TYPE_IS_HERE: 39,
    TokenKind.MODULE_COMING_SOON: 40,
    TokenKind.MODULE_IS_HERE: 41,
    TokenKind.BAR_JUST_BEFORE_NULL: 42,
    TokenKind.EXTERN: 43,
    TokenKind.VOID: 44,
    TokenKind.PUBLIC: 45,
    TokenKind.PRIVATE: 46,
    TokenKind.INTERNAL: 47,
    TokenKind.GLOBAL: 48,
    TokenKind.STATIC: 49,
    TokenKind.MEMBER: 50,
    TokenKind.CLASS: 51,
    TokenKind.ABSTRACT: 52,
    TokenKind.OVERRIDE: 53,
    TokenKind.DEFAULT: 54,
    TokenKind.CONSTRUCTOR: 55,
    TokenKind.INHERIT: 56,
    TokenKind.GREATER_RBRACK: 57,
    TokenKind.STRUCT: 58,
    TokenKind.SIG: 59,
    TokenKind.BAR: 60,
    TokenKind.RBRACK: 61,
    TokenKind.RBRACE_COMING_SOON: 62,
    TokenKind.RBRACE_IS_HERE: 63,
    TokenKind.MINUS: 64,
    TokenKind.DOLLAR: 65,
    TokenKind.BAR_RBRACK: 66,
    TokenKind.BAR_RBRACE: 67,
    TokenKind.UNDERSCORE: 68,
    TokenKind.SEMICOLON_SEMICOLON: 69,
    TokenKind.LARROW: 70,
    TokenKind.EQUALS: 71,
    TokenKind.LBRACK: 72,
    TokenKind.LBRACK_BAR: 73,
    TokenKind.LBRACE_BAR: 74,
    TokenKind.LBRACK_LESS: 75,
    TokenKind.QMARK: 76,
    TokenKind.QMARK_QMARK: 77,
    TokenKind.DOT: 78,
    TokenKind.COLON: 79,
    TokenKind.COLON_COLON: 80,
    TokenKind.COLON_GREATER: 81,
    TokenKind.COLON_QMARK_GREATER: 82,
    TokenKind.COLON_QMARK: 83,
    TokenKind.COLON_EQUALS: 84,
    TokenKind.SEMICOLON: 85,
    TokenKind.WHEN: 86,
    TokenKind.WHILE: 87,
    TokenKind.WHILE_BANG: 88,
    TokenKind.WITH: 89,
    TokenKind.HASH: 90,
    TokenKind.AMP: 91,
    TokenKind.AMP_AMP: 92,
    TokenKind.QUOTE: 93,
    TokenKind.LPAREN: 94,
    TokenKind.RPAREN: 95,
    TokenKind.RPAREN_COMING_SOON: 96,
    TokenKind.RPAREN_IS_HERE: 97,
    TokenKind.STAR: 98,
    TokenKind.COMMA: 99,
    TokenKind.RARROW: 100,
    TokenKind.GREATER_BAR_RBRACK: 101,
    TokenKind.GREATER_BAR_RBRACE: 102,
    TokenKind.LPAREN_STAR_RPAREN: 103,
    TokenKind.OPEN: 104,
    TokenKind.OR: 105,
    TokenKind.REC: 106,
    TokenKind.THEN: 107,
    TokenKind.TO: 108,
    TokenKind.TRUE: 109,
    TokenKind.TRY: 110,
    TokenKind.TYPE: 111,
    TokenKind.VAL: 112,
    TokenKind.INLINE: 113,
    TokenKind.INTERFACE: 114,
    TokenKind.INSTANCE: 115,
    TokenKind.CONST: 116,
    TokenKind.LAZY: 117,
    TokenKind.OLAZY: 118,
    TokenKind.MATCH: 119,
    TokenKind.MATCH_BANG: 120,
    TokenKind.MUTABLE: 121,
    TokenKind.NEW: 122,
    TokenKind.OF: 123,
    TokenKind.EXCEPTION: 124,
    TokenKind.FALSE: 125,
    TokenKind.FOR: 126,
    TokenKind.FUN: 127,
    TokenKind.FUNCTION: 128,
    TokenKind.IF: 129,
    TokenKind.IN: 130,
    TokenKind.JOIN_IN: 131,
    TokenKind.FINALLY: 132,
    TokenKind.DO_BANG: 133,
    TokenKind.AND: 134,
    TokenKind.AS: 135,
    TokenKind.ASSERT: 136,
    TokenKind.OASSERT: 137,
    TokenKind.ASR: 138,
    TokenKind.BEGIN: 139,
    TokenKind.DO: 140,
    TokenKind.DONE: 141,
    TokenKind.DOWNTO: 142,
    TokenKind.ELSE: 143,
    TokenKind.ELIF: 144,
    TokenKind.END: 145,
    TokenKind.DOT_DOT: 146,
    TokenKind.DOT_DOT_HAT: 147,
    TokenKind.BAR_BAR: 148,
    TokenKind.UPCAST: 149,
    TokenKind.DOWNCAST: 150,
    TokenKind.NULL: 151,
    TokenKind.RESERVED: 152,
    TokenKind.MODULE: 153,
    TokenKind.NAMESPACE: 154,
    TokenKind.DELEGATE: 155,
    TokenKind.CONSTRAINT: 156,
    TokenKind.BASE: 157,
    TokenKind.LQUOTE: 158,
    TokenKind.RQUOTE: 159,
    TokenKind.RQUOTE_DOT: 160,
    TokenKind.RQUOTE_BAR_RBRACE: 161,
    TokenKind.PERCENT_OP: 162,
    TokenKind.BINDER: 163,
    TokenKind.LESS: 164,
    TokenKind.GREATER: 165,
    TokenKind.LET: 166,
    TokenKind.YIELD: 167,
    TokenKind.YIELD_BANG: 168,
    TokenKind.AND_BANG: 169,
    TokenKind.BIGNUM: 170,
    TokenKind.DECIMAL: 171,
    TokenKind.CHAR: 172,
    TokenKind.IEEE64: 173,
    TokenKind.IEEE32: 174,
    TokenKind.UNATIVEINT: 175,
    TokenKind.UINT64: 176,
    TokenKind.UINT32: 177,
    TokenKind.UINT16: 178,
    TokenKind.UINT8: 179,
    TokenKind.NATIVEINT: 180,
    TokenKind.INT64: 181,
    TokenKind.INT32: 182,
    TokenKind.INT32_DOT_DOT: 183,
    TokenKind.INT16: 184,
    TokenKind.INT8: 185,
    TokenKind.FUNKY_OPERATOR_NAME: 186,
    TokenKind.ADJACENT_PREFIX_OP: 187,
    TokenKind.PLUS_MINUS_OP: 188,
    TokenKind.INFIX_AMP_OP: 189,
    TokenKind.INFIX_STAR_DIV_MOD_OP: 190,
    TokenKind.PREFIX_OP: 191,
    TokenKind.INFIX_BAR_OP: 192,
    TokenKind.INFIX_AT_HAT_OP: 193,
    TokenKind.INFIX_COMPARE_OP: 194,
    TokenKind.INFIX_STAR_STAR_OP: 195,
    TokenKind.HASH_IDENT: 196,
    TokenKind.IDENT: 197,
    TokenKind.KEYWORD_STRING: 198,
    TokenKind.LBRACE: 199,
    TokenKind.RBRACE: 200,
    TokenKind.INTERP_STRING_END: 201,
    TokenKind.INTERP_STRING_PART: 202,
    TokenKind.INTERP_STRING_BEGIN_PART: 203,
    TokenKind.INTERP_STRING_BEGIN_END: 204,
    TokenKind.STRING: 205,
    TokenKind.BYTEARRAY: 206,
}


def escape_lexeme(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\t", "\\t").replace("\r", "\\r").replace("\n", "\\n")


def format_official_token(token: Token) -> str | None:
    if token.kind == TokenKind.EOF or token.range is None:
        return None
    if token.kind in {TokenKind.WHITESPACE, TokenKind.INACTIVECODE} and "\n" in token.text:
        return None

    start_line = token.range.start.line
    start_col = token.range.start.column + 1
    end_col = token.range.end.column
    tag = OFFICIAL_TOKEN_TAGS[token.kind]
    full_length = (
        token.value["full_length"]
        if isinstance(token.value, dict) and "full_length" in token.value
        else len(token.text)
    )

    return (
        f"{start_line}:{start_col}:{end_col}\t"
        f"{token.kind.name}\t"
        f"{escape_lexeme(token.text)}\t"
        f"{tag}\t"
        f"{full_length}"
    )


def format_official_tokens(tokens: Iterable[Token]) -> str:
    lines = [line for token in tokens if (line := format_official_token(token)) is not None]
    return "\n".join(lines)
