from __future__ import annotations

from pathlib import Path

from .automata import CompiledSpec, compile_spec
from .parser import parse_fsl


def generate_text(
    fsl_text: str,
    *,
    filename: str = "<string>",
    unicode: bool = True,
    case_insensitive: bool = False,
    module_name: str = "generated_lexer",
) -> str:
    spec = parse_fsl(fsl_text, filename)
    compiled = compile_spec(spec, unicode=unicode, case_insensitive=case_insensitive)
    return emit_python(compiled, module_name=module_name)


def generate(
    input_fsl: str | Path,
    output_py: str | Path,
    *,
    unicode: bool = True,
    case_insensitive: bool = False,
    module_name: str = "generated_lexer",
) -> None:
    input_path = Path(input_fsl)
    output_path = Path(output_py)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        generate_text(
            input_path.read_text(encoding="utf-8-sig"),
            filename=str(input_path),
            unicode=unicode,
            case_insensitive=case_insensitive,
            module_name=module_name,
        ),
        encoding="utf-8",
    )


def emit_python(compiled: CompiledSpec, *, module_name: str) -> str:
    transitions = {
        state.id: dict(sorted(state.transitions.items()))
        for state in compiled.states
        if state.transitions
    }
    actions = {state.id: state.accepted[0][1] for state in compiled.states if state.accepted}
    rules = {
        rule.name: {
            "start_state": rule.start_state,
            "action_sources": list(rule.action_sources),
        }
        for rule in compiled.rules
    }
    return (
        "# Generated by fslexpy. Do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        "from fslexpy.runtime import LexBuffer, TableLexer\n\n"
        f"MODULE_NAME = {module_name!r}\n"
        f"TRANSITIONS = {transitions!r}\n"
        f"ACTIONS = {actions!r}\n"
        f"RULES = {rules!r}\n\n"
        "def build(action_handlers):\n"
        "    return TableLexer(TRANSITIONS, ACTIONS, action_handlers)\n\n"
        "def start_state(rule_name):\n"
        "    return RULES[rule_name]['start_state']\n"
        "\n"
        "def interpret(rule_name, lexbuf):\n"
        "    return build({}).interpret(start_state(rule_name), lexbuf)\n"
        "\n"
        "def run(rule_name, lexbuf, action_handlers):\n"
        "    action_id = interpret(rule_name, lexbuf)\n"
        "    return action_handlers[rule_name][action_id](lexbuf)\n"
    )
